1.product-introduction=产品简介
2.product-architecture=产品架构
2.deployment-guide=部署指南
3.user-guide=用户指南
1.console=管理控制台
3.user-center=个人中心
2.users-and-privileges=用户及权限
3.manage-data-sources=数据源管理
1.add-a-data-source=添加数据源
4.data-migration=数据迁移
3.create-a-data-migration-project=创建数据迁移项目
4.manage-data-migration-projects=管理数据迁移项目
5.data-synchronization=数据同步
3.create-a-synchronization-project=创建数据同步项目
4.manage-data-synchronization-projects=管理数据同步项目
6.o-m-manual=运维监控
2.server=机器
3.components=组件
1.store=Store
2.connector=Connector
3.jdbcwriter=JDBCWriter
4.checker=Checker
4.o-m-tickets=运维工单
5.description-of-component-parameters=组件参数说明
1.store-parameters=Store 组件参数说明
2.connector-parameters=Connector 组件参数说明
7.system-management=系统管理
2.alert-center=告警中心
4.system-parameters=系统参数
5.alarm-reference=告警参考
6.api-reference=API 参考
7.upgrade-guide=升级指南