100.product-introduction=Product Introduction
200.product-architecture=Architecture
200.deployment-guide=Deployment Guide
300.user-guide=User Guide
100.console=OMS Community Edition console
300.user-center=User center
200.users-and-privileges=Users and privileges
300.manage-data-sources=Manage data sources
100.add-a-data-source=Add a data source
400.data-migration=Data migration
300.create-a-data-migration-project=Create a data migration project
400.manage-data-migration-projects=Manage data migration projects
500.data-synchronization=Data synchronization
300.create-a-synchronization-project=Create a data synchronization project
400.manage-data-synchronization-projects=Manage data synchronization projects
600.o-m-manual=OPS & Monitoring
200.server=Server
300.components=Components
100.store=Store
200.connector=Connector
300.jdbcwriter=JDBCWriter
400.checker=Checker
400.o-m-tickets=O&M ticket
500.description-of-component-parameters=Component parameters
100.store-parameters=Store parameters
200.connector-parameters=Connector parameters
700.system-management=System management
200.alert-center=Alert center
400.system-parameters=System Parameters
500.alarm-reference=Alert Reference
600.api-reference=API Reference
700.upgrade-guide=Upgrade Guide
