1.product-introduction=Product Introduction
2.product-architecture=Architecture
2.deployment-guide=Deployment Guide
3.user-guide=User Guide
1.console=OMS Community Edition console
3.user-center=User center
2.users-and-privileges=Users and privileges
3.manage-data-sources=Manage data sources
1.add-a-data-source=Add a data source
4.data-migration=Data migration
3.create-a-data-migration-project=Create a data migration project
4.manage-data-migration-projects=Manage data migration projects
5.data-synchronization=Data synchronization
3.create-a-synchronization-project=Create a data synchronization project
4.manage-data-synchronization-projects=Manage data synchronization projects
6.6.o-m-manual=OPS & Monitoring
2.server=Server
3.components=Components
1.store=Store
2.connector=Connector
3.jdbcwriter=JDBCWriter
4.checker=Checker
4.o-m-tickets=O&M ticket
5.description-of-component-parameters=Component parameters
1.store-parameters=Store parameters
2.connector-parameters=Connector parameters
7.system-management=System management
2.alert-center=Alert center
4.system-parameters=System Parameters
5.alarm-reference=Alert Reference
6.api-reference=API Reference
7.upgrade-guide=Upgrade Guide