200.product-introduction=OMS 社区版简介
300.architecture=系统架构
300.quick-start=快速上手
400.deployment-guide=部署 OMS 社区版
500.oms-console=管理控制台
300.user-center=个人中心
600.data-migration=数据迁移
1500.manage-data-migration-projects=管理数据迁移项目
1600.migration-function-introduction=功能介绍
1700.supported-ddl-operations-for-incremental-migration-and-limits=同步 DDL 的支持范围和使用限制
100.mysql-to-obmysql=MySQL 数据库至 OceanBase 社区版的同步 DDL
200.create-table=创建表 CREATE TABLE
400.alter-table=修改表 ALTER TABLE
1000.mysql-incompatible=MySQL 数据库和 OceanBase 社区版的 DDL 不兼容点
200.create-table-incompatible=创建表不兼容点
300.alter-table-incompatible=修改表不兼容点
700.data-synchronization=数据同步
1200.sync-function-introduction=功能介绍
1100.manage-a-data-synchronization-projects=管理数据同步项目
1200.sync-function-introduction=功能介绍
800.create-and-manage-data-sources=新建及管理数据源
100.create-a-data-source=新建数据源
200.manage-data-sources=管理数据源
900.o-m-manual=运维监控
300.server=机器
400.components=组件
100.store=Store
200.connector=Connector
300.jdbcwriter=JDBCWriter
400.checker=Checker
500.o-m-tickets=运维任务
1000.system-management=系统管理
100.permission-management=权限管理
200.alert-center=告警中心
400.system-parameters=系统参数
1100.o-m-guide=运维 OMS 社区版
400.store-component-parameters=Store 组件参数说明
500.component-parameters=组件参数说明
400.sink-plugin=Sink Plugin
800.connector-parameters=Connector 组件参数说明
1200.reference-guide=参考指南
100.api-reference=API 参考
300.alarm-reference=告警参考
1400.faq=常见问题
100.general-o-m=一般运维
200.project-diagnosis=项目诊断
300.ops-monitoring=运维监控
400.data-sync=数据同步
100.sync-data-to-message-queue=同步到消息队列常见问题
500.data-migration-1=数据迁移
400.full-migration=全量迁移
300.full-faq=全量常见问题
500.incremental-synchronization=增量同步
1000.deployment=安装部署