100.product-introduction=产品简介
200.product-architecture=产品架构
200.deployment-guide=部署指南
300.user-guide=用户指南
100.console=管理控制台
300.user-center=个人中心
200.users-and-privileges=用户及权限
300.manage-data-sources=数据源管理
100.add-a-data-source=添加数据源
400.data-migration=数据迁移
300.create-a-data-migration-project=创建数据迁移项目
400.manage-data-migration-projects=管理数据迁移项目
500.data-synchronization=数据同步
300.create-a-synchronization-project=创建数据同步项目
400.manage-data-synchronization-projects=管理数据同步项目
600.o-m-manual=运维监控
200.server=机器
300.components=组件
100.store=Store
200.connector=Connector
300.jdbcwriter=JDBCWriter
400.checker=Checker
400.o-m-tickets=运维工单
500.description-of-component-parameters=组件参数说明
100.store-parameters=Store 组件参数说明
200.connector-parameters=Connector 组件参数说明
700.system-management=系统管理
200.alert-center=告警中心
400.system-parameters=系统参数
500.alarm-reference=告警参考
600.api-reference=API 参考
700.upgrade-guide=升级指南
