200.product-introduction=OMS Community Edition Introduction
300.architecture=Architecture
300.quick-start=Quick Start
400.deployment-guide=Deploy OMS Community Edition
500.oms-console=OMS Community Edition console
300.user-center=User center
600.data-migration=Data migration
1500.manage-data-migration-projects=Manage data migration projects
1600.migration-function-introduction=Features
1700.supported-ddl-operations-for-incremental-migration-and-limits=Supported DDL operations in incremental migration and limits
100.mysql-to-obmysql=DDL synchronization from MySQL database to OceanBase Community Edition
200.create-table=CREATE TABLE
400.alter-table=ALTER TABLE
1000.mysql-incompatible=DDL incompatibilities between MySQL database and OceanBase Community Edition
200.create-table-incompatible=Incompatibilities of the CREATE TABLE statement
300.alter-table-incompatible=Incompatibilities of the ALTER TABLE statement
700.data-synchronization=Data synchronization
1100.manage-a-data-synchronization-projects=Manage data synchronization projects
1200.sync-function-introduction=Features
800.create-and-manage-data-sources=Create and manage data sources
100.create-a-data-source=Create data sources
200.manage-data-sources=Manage data sources
900.o-m-manual=OPS & Monitoring
300.server=Server
400.components=Components
100.store=Store
200.incr-sync=Incr-Sync
300.full-import=Full-Import
400.full-verify=Full-Verification
500.o-m-tickets=O&M Task
1000.system-management=System management
100.permission-management=Permission Management
200.alert-center=Alert center
400.system-parameters=System parameters
1100.o-m-guide=OMS Community Edition O&M
300.o-m-components=Component O&M
400.component-tuning=Component tuning
500.component-parameters=Component parameters
300.source-plugin=Source Plugin
400.sink-plugin=Sink Plugin
500.store-component-parameters=Store parameters
1200.reference-guide=Reference Guide
100.api-reference=API Reference
300.alarm-reference=Alert Reference
1300.upgrade-guide=Upgrade Guide
1400.faq=FAQ
100.general-o-m=General O&M
200.project-diagnosis=Project diagnostics
300.ops-monitoring=OPS & monitoring
400.data-sync=Data synchronization
100.sync-data-to-message-queue=FAQ about synchronization to a message queue
500.data-migration-1=Data migration
400.full-migration=Full migration
300.full-faq=FAQ about full migration
500.incremental-synchronization=Incremental synchronization
1000.deployment=Installation and deployment
