100.product-introduction=产品简介
200.product-architecture=产品架构
200.deployment-guide=部署指南
300.console=管理控制台
300.user-center=个人中心
500.data-migration=数据迁移
300.create-a-data-migration-project=创建数据迁移项目
400.manage-data-migration-projects=管理数据迁移项目
600.data-source-management=数据源管理
100.add-a-data-source=添加数据源
700.o-m-and-monitoring=运维监控
200.server=机器
300.store=Store
400.jdbcwriter=JDBCWriter
500.checker=Checker
600.o-m-tickets=运维工单
700.description-of-component-parameters=组件参数说明
100.store-component-parameters=Store 组件参数说明
800.system-management=系统管理
200.alert-center=告警中心
